Admin/Controllers/PatientController.cs
using ClinicModels.Models;
using ClinicModels.Models.ViewBag.ViewModel;
using DataAcsses.Db;
using DataAcsses.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Numerics;
using X.PagedList.Extensions;
using static ClinicModels.Models.ViewBag.ViewModel.PatientVM;

namespace ClinicProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PatientController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public PatientController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [HttpGet]
        public IActionResult Index(string searchString, int? page)
        {
            var patient = _unitOfWork.patientRepository
                .GetAll().Where(u => u.IsDeleted == true);
            if (!string.IsNullOrEmpty(searchString))
            {
                patient = patient
                    .Where(d => d.FirstName.Contains(searchString)
                    || d.LastName.Contains(searchString) ||
                    d.Phone.Contains(searchString) ||
                    d.Email.Contains(searchString));
            }
            int pageSize = 10; // عدد العناصر في كل صفحة
            int pageNumber = page ?? 1;  //الصفحة الحالية 
            return View(patient.ToPagedList(pageNumber, pageSize));
        }
        public IActionResult Upsert(int id)
        {
            PatientVM patientVM = new()
            {
                GenderList = Enum.GetValues(typeof(Gender)).Cast<Gender>().Select(g => new SelectListItem
                {
                    Text = g.ToString(),
                    Value = g.ToString()
                }).ToList(),
                patient = new Patient()
            };

            if (id == null || id == 0)
            {
                //create
                return View(patientVM);
            }
            else
            {
                //update
                patientVM.patient = _unitOfWork.patientRepository.Get(u => u.Id == id);
                return View(patientVM);
            }
        }
        [HttpPost]
        public IActionResult Upsert(Patient patient)
        {
            if (ModelState.IsValid)
            {
                if (patient.Id == 0)
                {
                    _unitOfWork.patientRepository.Add(patient);

                }
                else
                {
                    _unitOfWork.patientRepository.Update(patient);

                }

            }

            _unitOfWork.Save();


            return RedirectToAction("Index");

        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var patient = _unitOfWork.patientRepository.Get(u => u.Id == id);
            if (patient == null)
            {
                return NotFound();
            }

            return View(patient);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var patient = _unitOfWork.patientRepository.Get(u => u.Id == id);
            if (patient == null)
            {
                return NotFound();
            }

            patient.IsDeleted = false;
            _unitOfWork.patientRepository.Update(patient);
            _unitOfWork.Save();

            TempData["success"] = "Patient deleted successfully";
            return RedirectToAction(nameof(Index));
        }
    }
}




Admin/Views/Patient/Delete.cshtml
@model Patient

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Confirm Deletion</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container mt-5">
        <h1>Confirm Deletion</h1>
        <h3>Are you sure you want to delete this Patient ?</h3>
        <div>
            <h4>@Model.FirstName @Model.LastName</h4>
            <hr />
            <dl class="row">
               
                <dt class="col-sm-2">
                    Phone
                </dt>
                <dd class="col-sm-10">
                    @Model.Phone
                </dd>
                <dt class="col-sm-2">
                    Email
                </dt>
                <dd class="col-sm-10">
                    @Model.Email
                </dd>
                <dt class="col-sm-2">
                    Gender
                </dt>
                <dd class="col-sm-10">
                    @Model.Gender
                </dd>
               
               
            </dl>

            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <button type="submit" class="btn btn-danger">Delete</button>
                <a asp-action="Index" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</body>
</html>

Admin/Views/Patient/Index.cshtml





@model X.PagedList.IPagedList<Patient>
@using X.PagedList.Mvc.Core

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Doctor List</title>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet" />
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script type="text/javascript">
        $(document).ready(function ()
        {
            setTimeout(function ()
            { $(".alert-success").fadeOut("slow");
            }, 2000); 
             //2000ms = 2 seconds 
        }); 
        </script>
    
    </head>
    <body>
        <div class="container mt-5">
            <h1>Patient List</h1>
    
            @if (TempData["success"] != null)
            {
                <div class="alert alert-success">@TempData["success"]</div>
            }
    
            <form method="get" action="/Patient/Index">
                <div class="form-group">
                    <input type="text" name="searchString" class="form-control" placeholder="Search..." value="@Context.Request.Query["searchString"]" />
                    <button type="submit" class="btn btn-primary mt-2">Search</button>
                </div>
            </form>
    
            <div class="d-flex justify-content-end mb-3">
                <a asp-action="Upsert" class="btn btn-primary">Create New Patient</a>
            </div>
             <table class="table table-bordered table-striped">
                 <thead>
                          <tr>
                              <th>Name</th>
                              <th>Phone</th>
                              <th>Email</th>
                              <th>Gender</th>                  
                              <th>Analysis</th>
                              <th>RequiredRays</th>
                              <th>DiseaseStatus</th>
                              <th>PatientComplaint</th>
                              <th>PatientDiagnosis</th>
                              <th></th>
                              
                          </tr>
                 </thead>
                 <tbody>
                     @foreach (var obj in Model.OrderBy(u => u.Id))
                     {
                         <tr>
                         
                             <td>@obj.FirstName@obj.LastName</td>
                             <td>@obj.Phone</td>
                             <td>@obj.Email</td>
                             <td>@obj.Gender</td>
                             <td>@obj.Analysis</td>
                             <td>@obj.RequiredRays</td>
                             <td>@obj.DiseaseStatus</td>
                             <td>@obj.PatientComplaint</td>
                             <td>@obj.PatientDiagnosis</td>
             
                             <td>
                                 <a asp-action="Upsert" asp-route-id="@obj.Id" class="btn btn-primary">Edit</a>
                                 <a asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger">Delete</a>
                             </td>
                         </tr>
                     }
                 </tbody>
             </table>
    
            <div class="d-flex justify-content-center">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
            </div>
        </div>
    </body>
</html>

Admin/Views/Patient/Upsert.cshtml
@model PatientVM

<div class="card shadow-border-0 mt-4">
    <div class="card-header bg-body-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-bg-dark py-2"> @(Model.patient.Id != 0 ? "Update" : "Create")Patient</h2>
            </div>
        </div>
        <div class="card-body p-4">
        </div>
    </div>

</div>
<form method="post" asp-controller="Patient" asp-action="Upsert">
    <input asp-for="patient.Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Creat New Patient</h2>
            <hr />
        </div>

        @*<div asp-validation-summary="ModelOnly"></div>*@
        <div class="mb-3 row p-1">
            <label asp-for="patient.FirstName" class="p-0"></label>
            <input asp-for="patient.FirstName" class="form-control" />
            <span asp-validation-for="patient.FirstName" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="patient.LastName" class="p-0"></label>
            <input asp-for="patient.LastName" class="form-control" />
            <span asp-validation-for="patient.LastName" class="text-danger"></span>
        </div>


        <div class="mb-3 row p-1">
            <label asp-for="patient.DateOfBirth" class="p-0"></label>
            <input asp-for="patient.DateOfBirth" class="form-control" />
            <span asp-validation-for="patient.DateOfBirth" class="text-danger"></span>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="patient.Phone" class="p-0"></label>
            <input asp-for="patient.Phone" class="form-control" />
            <span asp-validation-for="patient.Phone" class="text-danger"></span>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="patient.Email" class="p-0"></label>
            <input asp-for="patient.Email" class="form-control" />
            <span asp-validation-for="patient.Email" class="text-danger"></span>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="patient.Gender" class="p-0"></label>
            <select asp-for="patient.Gender" class="form-control" asp-items="Model.GenderList"></select>
            <span asp-validation-for="patient.Gender" class="text-danger"></span>
        </div>

        <div class="mb-3 row p-1">
            <label asp-for="patient.BloodType" class="p-0"></label>
            <input asp-for="patient.BloodType" class="form-control" />
            <span asp-validation-for="patient.BloodType" class="text-danger"></span>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="patient.Weight" class="p-0"></label>
            <input asp-for="patient.Weight" class="form-control" />
            <span asp-validation-for="patient.Weight" class="text-danger"></span>

        </div>    
        <div class="mb-3 row p-1">
            <label asp-for="patient.Analysis" class="p-0"></label>
            <input asp-for="patient.Analysis" class="form-control" />
            <span asp-validation-for="patient.Analysis" class="text-danger"></span>

        </div>  
        <div class="mb-3 row p-1">
            <label asp-for="patient.RequiredRays" class="p-0"></label>
            <input asp-for="patient.RequiredRays" class="form-control" />
            <span asp-validation-for="patient.RequiredRays" class="text-danger"></span>

        </div>   
        <div class="mb-3 row p-1">
            <label asp-for="patient.DiseaseStatus" class="p-0"></label>
            <input asp-for="patient.DiseaseStatus" class="form-control" />
            <span asp-validation-for="patient.DiseaseStatus" class="text-danger"></span>

        </div> 
           
        <div class="mb-3 row p-1">
            <label asp-for="patient.PatientComplaint" class="p-0"></label>
            <input asp-for="patient.PatientComplaint" class="form-control" />
            <span asp-validation-for="patient.PatientComplaint" class="text-danger"></span>

        </div> 
           
        <div class="mb-3 row p-1">
            <label asp-for="patient.PatientDiagnosis" class="p-0"></label>
            <input asp-for="patient.PatientDiagnosis" class="form-control" />
            <span asp-validation-for="patient.PatientDiagnosis" class="text-danger"></span>

        </div>
        <div class="row pt-2">
            <div class="col-6 col-md-3">
                @if (Model.patient.Id != 0)
                {
                    <button type="submit" class="btn btn-primary from-control">Update</button>
                }
                else
                {
                    <button type="submit" class="btn btn-primary from-control">Create</button>
                }
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Patient" asp-action="Index" class="btn btn-secondary border from-control">
                    Back to list
                </a>
            </div>
        </div>



    </div>
</form>
@section Scripts {
    @{
        <partail name="_ValidationScriptsPartial" />
    }
}