Admin/Controllers/ClinicController.cs
using ClinicModels.Models;
using ClinicModels.Models.ViewBag.ClinicEmployeeVB;
using ClinicModels.Models.ViewBag.ClinicVB;
using ClinicModels.Models.ViewBag.SalaryEmpolyeeVB;
using ClinicModels.Models.ViewBag.ViewModel;
using DataAcsses.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Utitiy;
using X.PagedList.Extensions;




namespace ClinicProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ClinicController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;



        public ClinicController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        [HttpGet]
        public IActionResult Index(string searchString, int? page)
        {
            var clinic = _unitOfWork.clinicRepository
                .GetAll(includeProperties: "doctor").Where(u => u.IsDeleted ==true);
            if (!string.IsNullOrEmpty(searchString))
            {
                clinic = clinic
                    .Where(d => d.ClinicName.Contains(searchString)
                    || d.doctor.FirstName.Contains(searchString)
                    || d.Address.Contains(searchString));
                   
                    
            }
            int pageSize = 10; // عدد العناصر في كل صفحة
            int pageNumber = page ?? 1;  //الصفحة الحالية 
            return View(clinic.ToPagedList(pageNumber, pageSize));
        }

        public IActionResult Create()
        {
            ViewBag.clinicList = _unitOfWork.doctorRepository.GetAll().Where(u => u.IsDeleted == true).Select(u => new SelectListItem

            {

                Text = $"{u.FirstName} {u.LastName}",
                Value = u.Id.ToString()
            });
            var clinic = new ClinicCreation();

            return View(clinic);
        }
    
         [HttpPost]
         public IActionResult Create(ClinicCreation clinic)
         {
           
             if (ModelState.IsValid)
             {
                var clinicASEntity = new Clinic()
                {
                    DoctorId = clinic.DoctorId,
                    ClinicName = clinic.ClinicName,
                    Address = clinic.Address,
                    Date = clinic.Date,
                    OpeningTime = clinic.OpeningTime,
                    ClosingTime = clinic.ClosingTime,
                    IsOpen = clinic.IsOpen,
                    Notes = clinic.Notes,
                    WorkingDays = clinic.WorkingDays

                };
                _unitOfWork.clinicRepository.Add(clinicASEntity);
                 _unitOfWork.Save();
                 return RedirectToAction("Index");
             }
             return NotFound();
         }
        //_unitOfWork.clinicRepository.Update(clinicvm.clinic);
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            // Fetch the SalaryEmployee entity
            var clinic = _unitOfWork.clinicRepository.Get(x => x.Id == id);
            if (clinic == null)
            {
                return NotFound();
            }

            // Create the SalaryEmployeeEdit ViewModel and populate its properties
            var clinicEdit = new ClinicEdit
            {
                Id = clinic.Id,
                DoctorId = clinic.DoctorId,
                ClinicName = clinic.ClinicName,
                Address =clinic.Address,
                Date = clinic.Date,
                OpeningTime = clinic.OpeningTime,
                ClosingTime = clinic.ClosingTime,
               IsOpen= clinic.IsOpen,
               WorkingDays= clinic.WorkingDays,
               Notes= clinic.Notes
            };

            // Populate the ViewBag with necessary data
            ViewBag.doctorList = _unitOfWork.doctorRepository.GetAll().Select(u => new SelectListItem
            {
                Text = $"{u.FirstName} {u.LastName} ",
                Value = u.Id.ToString()
            }).ToList();

            return View(clinicEdit);
        }


        [HttpPost, ActionName("Edit")]
        public IActionResult Edit(ClinicEdit clinic)
        {

            if (ModelState.IsValid)
            {
                Clinic clinicAsEntity = new Clinic()
                {
                    Id = clinic.Id,
                    DoctorId = clinic.DoctorId,
                    ClinicName = clinic.ClinicName,
                    Address = clinic.Address,
                    Date = clinic.Date,
                    OpeningTime = clinic.OpeningTime,
                    ClosingTime = clinic.ClosingTime,
                    IsOpen = clinic.IsOpen,
                    WorkingDays = clinic.WorkingDays,
                    Notes = clinic.Notes

                };
               
                _unitOfWork.clinicRepository.Update(clinicAsEntity);
                _unitOfWork.Save();
                TempData["success"] = "Salary Employee Updated successfully";
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }




        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Clinic clinic = _unitOfWork.clinicRepository.GetAll(includeProperties: "doctor").FirstOrDefault(u => u.Id == id);


            if (clinic == null)
            {
                return NotFound();
            }
            return View(clinic);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {

            Clinic? obj = _unitOfWork.clinicRepository.GetAll(includeProperties: "doctor").FirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            obj.IsDeleted = false;
            _unitOfWork.clinicRepository.Update(obj);
            _unitOfWork.Save();
            TempData["success"] = "Clinic Deleted successfully";

            return RedirectToAction("Index");
        }

    }

} 


Admin/Views/Clinic/Create.cshtml
@model ClinicCreation

<div class="card shadow-border-0 mt-4">
    <div class="card-header bg-body-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
             <div class="col-12 text-center">
                         <h2 class="text-white py-2">Clinic</h2>
                     </div>
        </div>
        <div class="card-body p-4">
        </div>
    </div>

</div>

<form method="post" asp-controller="Clinic" asp-action="Create">
    
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Clinic</h2>
            <hr />
        </div>
    

        @*<div asp-validation-summary="ModelOnly"></div>*@
       
        <div class="mb-3 row p-1">
            <label asp-for="ClinicName" class="p-0"></label>
                <input asp-for="ClinicName" class="form-control" />
                <span asp-validation-for="ClinicName" class="text-danger"></span>
        </div>
        

        <div class="mb-3 row p-1">
            <label asp-for="Address" class="p-0"></label>
            <input asp-for="Address" class="form-control" />
            <span asp-validation-for="Address" class="text-danger"></span>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Date" class="p-0"></label>
            <input asp-for="Date" class="form-control" />
            <span asp-validation-for="Date" class="text-danger"></span>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="OpeningTime" class="p-0"></label>
            <input asp-for="OpeningTime" class="form-control" />
            <span asp-validation-for="OpeningTime" class="text-danger"></span>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="ClosingTime" class="p-0"></label>
            <input asp-for="ClosingTime" class="form-control" />
            <span asp-validation-for="ClosingTime" class="text-danger"></span>

        </div>
        
        <div class="mb-3 row p-1">
            <label asp-for="Notes" class="p-0"></label>
            <textarea asp-for="Notes" class="form-control"></textarea>
            <span asp-validation-for="Notes" class="text-danger"></span>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="WorkingDays" class="p-0"></label>
            <input asp-for="WorkingDays" class="form-control" />
            <span asp-validation-for="WorkingDays" class="text-danger"></span>

        </div>
       
            <div class="mb-3 row p-1">
                <label class ="p-0">Name Of Doctor</label>
            <select asp-for="DoctorId" asp-items="@(IEnumerable<SelectListItem>)ViewBag.clinicList" class="p-0">
                <option>--Select Doctor--</option>

            </select>
            
            <span asp-validation-for="DoctorId" class="text-danger"></span>
        </div>
        


        <div class="row pt-2">
            <div class="col-6 col-md-3">
             
                
                    <button type="submit" class="btn btn-primary from-control">Create</button>
                
            </div>

            <div class="col-6 col-md-3">
                <a asp-controller="Clinic" asp-action="Index" class="btn btn-secondary border from-control">
                    Back to list
                </a>
            </div>
        </div>
       



    </div>
</form>
@section Scripts {
    @{
        <partail name="_ValidationScriptsPartial" />
    }
}

Admin/Views/Clinic/Delete.cshtml
@model ClinicModels.Models.Clinic

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Confirm Deletion</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container mt-5">
        <h1>Confirm Deletion</h1>
        <h3>Are you sure you want to delete this Clinic Employee ?</h3>
        <div>
            <h4>@Model.ClinicName</h4>
            <hr />
            <dl class="row">

                <dt class="col-sm-2">
                    Address
                </dt>
                <dd class="col-sm-10">
                    @Model.Address
                </dd>
                <dt class="col-sm-2">
                    Doctor Name
                </dt>
                <dd class="col-sm-10">
                    @Model.doctor.FirstName @Model.doctor.LastName
                </dd>
             


            </dl>

            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <button type="submit" class="btn btn-danger">Delete</button>
                <a asp-action="Index" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</body>
</html>


Admin/Views/Clinic/Edit.cshtml
@model ClinicEdit

<div class="card shadow-border-0 mt-4">
    <div class="card-header bg-body-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Clinic</h2>
            </div>
        </div>
        <div class="card-body p-4">
        </div>
    </div>

</div>

<form method="post" asp-controller="Clinic" asp-action="Edit">

    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Clinic</h2>
            <hr />
        </div>


        @*<div asp-validation-summary="ModelOnly"></div>*@

        <div class="mb-3 row p-1">
            <label asp-for="ClinicName" class="p-0"></label>
            <input asp-for="ClinicName" class="form-control" />
            <span asp-validation-for="ClinicName" class="text-danger"></span>
        </div>


        <div class="mb-3 row p-1">
            <label asp-for="Address" class="p-0"></label>
            <input asp-for="Address" class="form-control" />
            <span asp-validation-for="Address" class="text-danger"></span>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Date" class="p-0"></label>
            <input asp-for="Date" class="form-control" />
            <span asp-validation-for="Date" class="text-danger"></span>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="OpeningTime" class="p-0"></label>
            <input asp-for="OpeningTime" class="form-control" />
            <span asp-validation-for="OpeningTime" class="text-danger"></span>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="ClosingTime" class="p-0"></label>
            <input asp-for="ClosingTime" class="form-control" />
            <span asp-validation-for="ClosingTime" class="text-danger"></span>

        </div>

        <div class="mb-3 row p-1">
            <label asp-for="Notes" class="p-0"></label>
            <textarea asp-for="Notes" class="form-control"></textarea>
            <span asp-validation-for="Notes" class="text-danger"></span>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="WorkingDays" class="p-0"></label>
            <input asp-for="WorkingDays" class="form-control" />
            <span asp-validation-for="WorkingDays" class="text-danger"></span>

        </div>

        <div class="mb-3 row p-1">
            <label class="p-0">Name Of Doctor</label>
            <select asp-for="DoctorId" asp-items="@(IEnumerable<SelectListItem>)ViewBag.doctorList" class="p-0">
                <option>--Select Doctor--</option>

            </select>

            <span asp-validation-for="DoctorId" class="text-danger"></span>
        </div>



        <div class="row pt-2">
            <div class="col-6 col-md-3">


                <button type="submit" class="btn btn-primary from-control">Update</button>

            </div>

            <div class="col-6 col-md-3">
                <a asp-controller="Clinic" asp-action="Index" class="btn btn-secondary border from-control">
                    Back to list
                </a>
            </div>
        </div>




    </div>
</form>
@section Scripts {
    @{
        <partail name="_ValidationScriptsPartial" />
    }
}

Admin/Views/Clinic/Index.cshtml

@model X.PagedList.IPagedList<Clinic>
@using X.PagedList.Mvc.Core

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Clinic List</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            setTimeout(function () {
                $(".alert-success").fadeOut("slow");
            }, 2000);
            //2000ms = 2 seconds
        });
    </script>

</head>
<body>
    <div class="container mt-5">
        <h1>Clinic List</h1>

        @if (TempData["success"] != null)
        {
            <div class="alert alert-success">@TempData["success"]</div>
        }

        <form method="get" action="/Admin/Clinic/Index">
            <div class="form-group">
                <input type="text" name="searchString" class="form-control" placeholder="Search..." value="@Context.Request.Query["searchString"]" />
                <button type="submit" class="btn btn-primary mt-2">Search</button>
            </div>
        </form>

        <div class="d-flex justify-content-end mb-3">
            <a asp-action="Create" class="btn btn-primary">Create New Clinic</a>
        </div>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ClinicName</th>
                    <th>Address</th>
                    <th>Date</th>
                    <th>OpeningTime</th>
                    <th>ClosingTime</th>
                    <th>IsOpen</th>
                    <th>doctorName</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var clinic in Model)
                {
                    <tr>
                        <td>@clinic.ClinicName</td>
                        <td>@clinic.Address</td>
                        <td>@clinic.Date</td>
                        <td>@clinic.OpeningTime</td>
                        <td>@clinic.ClosingTime</td>
                        <td>@clinic.IsOpen</td>
                        <td>@clinic.doctor.FirstName @clinic.doctor.LastName</td>

                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Clinic" asp-action="Edit" asp-route-id="@clinic.Id" class="btn btn-primary mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-controller="Clinic" asp-action="Delete" asp-route-id="@clinic.Id" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <div class="d-flex justify-content-center">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
        </div>
    </div>
</body>
</html>