Admin/Controllers/ClinicStoreController.cs
using ClinicModels.Models;
using DataAcsses.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList.Extensions;


namespace ClinicProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ClinicStoreController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        public ClinicStoreController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;

        }

        [HttpGet]
        public IActionResult Index(string searchString, int? page)
        {
            TempData["success"] = "Operation completed successfully";
            var clinicStore = _unitOfWork.clinicStoreRepository
                .GetAll(includeProperties: "clinic").Where(u => u.IsDeleted == true);
            if (!string.IsNullOrEmpty(searchString))
            {
                clinicStore = clinicStore
                       .Where(d => d.clinic.ClinicName.Contains(searchString)
                    || d.InstrumentName.Contains(searchString));



            }
            int pageSize = 10; // عدد العناصر في كل صفحة
            int pageNumber = page ?? 1;  //الصفحة الحالية 
            return View(clinicStore.ToPagedList(pageNumber, pageSize));
        }
        public IActionResult Upsert(int id)
        {

            ClinicStoreVM clinicstoreVM = new()
            {
                clinicstoreList = _unitOfWork.clinicRepository.GetAll().Select(u => new SelectListItem
                {
                    Text = u.ClinicName,
                    Value = u.Id.ToString()
                }),
                clinicstore = new ClinicStore()
            };


            if (id == null || id == 0)
            {
                //create
                return View(clinicstoreVM);
            }
            else
            {
                //update
                clinicstoreVM.clinicstore = _unitOfWork.clinicStoreRepository.Get(u => u.Id == id);
                return View(clinicstoreVM);
            }
        }
        [HttpPost]
        public IActionResult Upsert(ClinicStoreVM clinicStorevm)
        {
            if (clinicStorevm.clinicstore.Id == 0)
            {
                _unitOfWork.clinicStoreRepository.Add(clinicStorevm.clinicstore);

            }
            else
            {
                _unitOfWork.clinicStoreRepository.Update(clinicStorevm.clinicstore);

            }

            _unitOfWork.Save();
            TempData["success"] = "Clinic Store created/updated successfully";
            return RedirectToAction("Index");




        }
        //public IActionResult Edit(int? id)
        //{
        //    if (id == null || id == 0)
        //    {
        //        return NotFound();
        //    }
        //    ClinicStore ClinicStoreDb = _unitOfWork.clinicStoreRepository.Get(u => u.Id == id);


        //    if (ClinicStoreDb == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(ClinicStoreDb);

        //}
        //[HttpPost]
        //public IActionResult Edit(ClinicStore obj)
        //{

        //    if (!ModelState.IsValid)
        //    {
        //        _unitOfWork.clinicStoreRepository.Update(obj);
        //        _unitOfWork.clinicStoreRepository.Save();


        //        return RedirectToAction("Index");
        //    }
        //    return View();
        //}
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            ClinicStore ClinicStoreFormDb = _unitOfWork.clinicStoreRepository.Get(u => u.Id == id, includeProperties: "clinic");


            if (ClinicStoreFormDb == null)
            {
                return NotFound();
            }
            return View(ClinicStoreFormDb);

        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int? id)
        {

            ClinicStore obj = _unitOfWork.clinicStoreRepository.Get(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            obj.IsDeleted = false;
            _unitOfWork.clinicStoreRepository.Update(obj);
            _unitOfWork.Save();

            TempData["success"] = "Clinic Store deleted successfully";
            return RedirectToAction(nameof(Index));
        }
    }
}

Admin/Views/ClinicStore/Delete.cshtml
@model ClinicStore

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Confirm Deletion</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container mt-5">
        <h1>Confirm Deletion</h1>
        <h3>Are you sure you want to delete this Clinic Store?</h3>
        <div>
            <h4>@Model.clinic.ClinicName </h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    InstrumentName
                </dt>
                <dd class="col-sm-10">
                    @Model.InstrumentName
                </dd>
                <dt class="col-sm-2">
                    DateAdded
                </dt>
                <dd class="col-sm-10">
                    @Model.DateAdded
                <dt class="col-sm-2">
                    ExpiryDate
                </dt>
                <dd class="col-sm-10">
                    @Model.ExpiryDate
                </dd>
                <dt class="col-sm-2">
                    ExpiryDate
                </dt>
                <dd class="col-sm-10">
                    @Model.ExpiryDate
                </dd>
               
            </dl>

            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <button type="submit" class="btn btn-danger">Delete</button>
                <a asp-action="Index" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</body>
</html>

Admin/Views/ClinicStore/Index.cshtml
@model X.PagedList.IPagedList<ClinicStore>
@using X.PagedList.Mvc.Core

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Clinic Store List</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            setTimeout(function () {
                $(".alert-success").fadeOut("slow");
            }, 2000);
            //2000ms = 2 seconds
        });
    </script>

</head>
<body>
    <div class="container mt-5">
        <h1>Clinic Store List</h1>

        @if (TempData["success"] != null)
        {
            <div class="alert alert-success">@TempData["success"]</div>
        }

        <form method="get" action="/clinicStore/Index">
            <div class="form-group">
                <input type="text" name="searchString" class="form-control" placeholder="Search..." value="@Context.Request.Query["searchString"]" />
                <button type="submit" class="btn btn-primary mt-2">Search</button>
            </div>
        </form>

        <div class="d-flex justify-content-end mb-3">
            <a asp-action="Upsert" class="btn btn-primary">Create New Doctor</a>
        </div>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>اسـم العيــاده</th>
                <th>اســـم الخامـــه</th>
                <th>الكمــيه</th>
                <th>تاريــخ الانـتاج</th>
                <th>تاريــخ الانتهاء</th>
                
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>@obj.clinic.ClinicName</td>
                    <td>@obj.InstrumentName</td>
                    <td>@obj.Quantity</td>
                    <td>@obj.DateAdded</td>
                    <td>@obj.ExpiryDate</td>


                        <td>
                            <a asp-action="Upsert" asp-route-id="@obj.Id" class="btn btn-primary">Edit</a>
                            <a asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger">Delete</a>
                        </td>

                </tr>



            }
        </tbody>


    </table>
        <div class="d-flex justify-content-center">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
        </div>
    </div>
</body>
</html>

Admin/Views/ClinicStore/Upsert.cshtml
@model ClinicStoreVM

<div class="card shadow-border-0 mt-4">
    <div class="card-header bg-body-secondary bg-gradient m-lg-0 py-3">
        <div class="row">
            <div class="col-12 test-center">
                <h2 class="text-primary py-2">Clinic Store</h2>
            </div>
        </div>
        <div class="card-body p-4">
        </div>
    </div>

</div>
<form method="post" asp-controller="ClinicStore" asp-action="Upsert">
    <input asp-for="clinicstore.Id" hidden />

    <div class="border p-3 mt-4">
        <div class="col-12 text-center">
            <h2 class="text-primary py-2"> @(Model.clinicstore.Id != 0 ? "Update" : "Create") Clinic Store</h2>
        </div>

        @*<div asp-validation-summary="ModelOnly"></div>*@
        
        <div class="mb-3 row p-1">
            <label asp-for="clinicstore.InstrumentName" class="p-0"></label>
            <input asp-for="clinicstore.InstrumentName" class="form-control" />
            <span asp-validation-for="clinicstore.InstrumentName" class="text-danger"></span>
        </div>


        <div class="mb-3 row p-1">
            <label asp-for="clinicstore.Quantity" class="p-0"></label>
            <input asp-for="clinicstore.Quantity" class="form-control" />
            <span asp-validation-for="clinicstore.Quantity" class="text-danger"></span>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="clinicstore.DateAdded" class="p-0"></label>
            <input asp-for="clinicstore.DateAdded" class="form-control" />
            <span asp-validation-for="clinicstore.DateAdded" class="text-danger"></span>

        </div>
        <div class="mb-3 row p-1">
            <label asp-for="clinicstore.ExpiryDate" class="p-0"></label>
            <input asp-for="clinicstore.ExpiryDate" class="form-control" />
            <span asp-validation-for="clinicstore.ExpiryDate" class="text-danger"></span>

        </div>
        <div class="mb-3 row p-1">
            <label class="p-0">Name Of Clinic</label>
            <select asp-for="@Model.clinicstore.ClinicId" asp-items="@Model.clinicstoreList" class="p-0">
                <option>--Select The Clinic--</option>
            </select>

            <span asp-validation-for="clinicstore.ClinicId" class="text-danger"></span>
        </div>


        <div class="row pt-2">
            <div class="col-6 col-md-3">
                @if (Model.clinicstore.Id != 0)
                {
                    <button type="submit" class="btn btn-primary from-control">Update</button>
                }
                else
                {
                    <button type="submit" class="btn btn-primary from-control">Create</button>
                }
            </div>

            <div class="col-6 col-md-3">
                <a asp-controller="ClinicStore" asp-action="Index" class="btn btn-secondary border from-control">
                    Back to list
                </a>
            </div>
        </div>



    </div>
</form>
@section Scripts {
    @{
        <partail name="_ValidationScriptsPartial" />
    }
}